#!/usr/bin/env bash
{% set settings = salt['mc_burp.settings']() %}
{% if client != 'server_conf' %}{% set settings=settings['clients']%}{%endif%}
{% set data=settings[client] %}
MAILTO=""
{{cdata.cron_periodicity}} {{cdata.cron_cmd}}
* */3 * * * root /etc/burp/cleanup-burp-processes.sh
