---
{% set prefix = 'ms_localsettings_apparmor_' %}
{% for var in vars %}
{% if var.startswith(prefix) %}
{% set svar = var.replace(prefix, '') %}
{{svar}}: {{vars[var]|to_json}}
{% endif %}
{% endfor %}
