---
- name: "ms_localsettings_dns preflight check - SKIPTEST"
  debug:
    msg: '{{True}}'
  register: ms_localsettings_dns_can_run
  tags: ms_localsettings_dns
- include: run.yml
  when: '{{ ms_localsettings_dns_can_run.msg == True }}'
  tags: ms_localsettings_dns
