#!/usr/bin/env bash
{%- set vmdata = salt['mc_cloud_vm.settings']() %}
{%- set data = vmdata.vts.docker.defaults %}
export USE_DOCKER_BRIDGE="{{data.use_bridge}}"
export DOCKER_MAKINA_BRIDGE="{{data.bridge}}"
export DOCKER_MAKINA_ADDR="{{data.gateway}}"
export DOCKER_MAKINA_NETMASK="{{data.netmask_full}}"
export DOCKER_MAKINA_NETWORK="{{data.network}}/{{data.netmask}}"
export varrun="/var/run/docker"
export DOCKER_DOMAIN=""
export DOCKER_MAKINA_DOMAIN=""
# vim:set ft=sh et sts=4 ts=4 tw=80:
