#!/usr/bin/env bash
{%- set vmdata = salt['mc_cloud_vm.settings']() %}
{%- set data = vmdata.vts.lxc.defaults %}
export USE_LXC_BRIDGE="{{data.use_bridge}}"
export LXC_MAKINA_BRIDGE="{{data.bridge}}"
export LXC_MAKINA_ADDR="{{data.gateway}}"
export LXC_MAKINA_NETMASK="{{data.netmask_full}}"
export LXC_MAKINA_NETWORK="{{data.network}}/{{data.netmask}}"
export varrun="/var/run/lxc"
export LXC_DOMAIN=""
export LXC_MAKINA_DOMAIN=""
# vim:set ft=sh et sts=4 ts=4 tw=80:
