#!/usr/bin/env bash
export OWC=$(pwd)
cd "$(dirname "$(dirname "$(readlink -f ${0})")")"
. bin/ansible-wrapper-common
if [[ -z ${ANSIBLE_NOLIMIT} ]] && [[ -n ${ANSIBLE_TARGETS-} ]];then
    exec ${MS_VENV_PATH}/bin/${SCRIPT} -l "${ANSIBLE_TARGETS}" "${@}"
else
    exec ${MS_VENV_PATH}/bin/${SCRIPT} "${@}"
fi
# vim:set et sts=4 ts=4 tw=80:
