#!/usr/bin/env bash
export WC=$(pwd)
export A=$WC/ansible
export DA=$WC/.ansible
export OWC=${OWC:-${WC}}
export OA=$OWC/ansible
export ODA=$OWC/.ansible
export SCRIPT=$(basename ${0})
export MS_VENV_PATH="${MS_VENV_PATH-${WC}/venv}"
export CONF_PREFIXES="/etc/ansible"
export MODULE_PREFIXES="/usr/share/ansible/plugins"

if [ -e "${MS_VENV_PATH}/bin/activate" ]
then
    . "${MS_VENV_PATH}/bin/activate"
else
    warn "virtualenv not found in ${MS_VENV_PATH}"
fi


for p in "${WC}" "${OWC}" "${ODA}" "${OA}" "${DA}" "${A}";do
    CONF_PREFIXES="${p};${CONF_PREFIXES}"
    MODULE_PREFIXES="${p};${MODULE_PREFIXES}"
done

ANSIBLE_VARS="\
ANSIBLE_NOLIMIT
ANSIBLE_TARGETS
MS_REFRESH_CACHE
NO_MEMCACHE_RESTART
ANSIBLE_INVENTORY:::${WC}/etc/ansible/inventories/
ANSIBLE_SSH_CONTROL_PATH:::~/.assh_%%h.%%p-%%r
ANSIBLE_HOST_KEY_CHECKING:::False
ANSIBLE_NOCOWS:::False
ANSIBLE_LIBRARY:library:${MODULE_PREFIXES}
ANSIBLE_ROLES_PATH:roles:${CONF_PREFIXES}
ANSIBLE_ACTION_PLUGINS:plugins/action:${MODULE_PREFIXES}
ANSIBLE_CACHE_PLUGINS:plugins/cache:${MODULE_PREFIXES}
ANSIBLE_CALLBACK_PLUGINS:plugins/callback:${MODULE_PREFIXES}
ANSIBLE_LOOKUP_PLUGINS:plugins/lookup:${MODULE_PREFIXES}
ANSIBLE_CONNECTION_PLUGINS:plugins/connection:${MODULE_PREFIXES}
ANSIBLE_INVENTORY_PLUGINS:plugins/inventory:${MODULE_PREFIXES}
ANSIBLE_FILTER_PLUGINS:plugins/filter:${MODULE_PREFIXES}
ANSIBLE_TEST_PLUGINS:plugins/test:${MODULE_PREFIXES}
ANSIBLE_STRATEGY_PLUGINS:plugins/strategy:${MODULE_PREFIXES}"
i=0
while read line;do
    default=$(echo "$line:"|cut -d: -f4)
    var=$(echo "$line:"|cut -d: -f1)
    prefix=$(echo "$line:"|cut -d: -f2)
    paths=$(echo "$line:"|cut -d: -f3)
    subpaths=""
    eval 'val=$'"${var}"
    if [[ -n "${default}" ]] && [[ -z ${val} ]]; then
        if [[ -z ${val} ]];then
            eval ${var}'="'${default}'"'
        fi
    fi
    eval 'val=$'"${var}"
    if [[ -n "${paths}" ]] && [[ -z ${val} ]]; then
        for p in ${paths//;/ };do
            if [[ -z ${subpaths} ]]; then
                subpaths="${p}/${prefix}"
            else
                subpaths="${subpaths}:${p}/${prefix}"
            fi
        done
        eval ${var}'="'${subpaths}'"'
    fi
    eval 'val=$'"${var}"
    if [ -n ${val} ]; then
        eval 'export '${var}'="'${val}'"'
    fi
done <<< "${ANSIBLE_VARS}"

if [[ -n ${MS_ENV_DEBUG-} ]]; then
    env
    exit 1
fi
cd "${OWC}"
