#!/usr/bin/env bash
cd "$(dirname ${0})"
WC="$(pwd)"
MS_VENV_PATH="${MS_VENV_PATH-/salt-venv/salt}"
ANSIBLE_LIBRARY="${WC}/ansible:${ANSIBLE_LIBRARY}"
CLI_ARGS=""
if [ -e "ansible/modules" ];then
    CLI_ARGS="-M $"
warn() {
    echo "WARN: ${@}" >&2
}

die_in_error() {
    echo "ERROR: ${@}" >&2
    exit 1
}

if [ -e "${MS_VENV_PATH}/bin/activate" ] && [ -e "${MS_VENV_PATH}/bin/ansible" ]
then
    . "${MS_VENV_PATH}/bin/activate"
else
    warn "ansible virtualenv not found in ${MS_VENV_PATH}"
fi
if ! python << EOF
import mc_states
import ansible
EOF
then
    die_in_error "python prerequisites not found"
fi
if ! hash -r ansible >/dev/null 2>&1;then
    die_in_error "ansible executable not found"
fi
exec ansible "${@}"
# vim:set et sts=4 ts=4 tw=80:
