include:
  - makina-states.localsettings.hosts
  - makina-states.localsettings.network
  - makina-states.localsettings.git
  - makina-states.localsettings.localrc
  - makina-states.localsettings.pkgs
  - makina-states.localsettings.shell
  - makina-states.localsettings.locales
  - makina-states.localsettings.sudo
  - makina-states.localsettings.users
  - makina-states.localsettings.vim
