#!/bin/sh

### BEGIN INIT INFO
# Provides:             docker-net-amkina
# Required-Start:       $syslog $remote_fs docker
# Required-Stop:        $syslog $remote_fs docker
# Should-Start:
# Should-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Linux Containers Network Configuration (makina)
# Description:          Linux Containers Network Configuration (makina)
# X-Start-Before:
# X-Stop-After:
# X-Interactive:        true
### END INIT INFO

# Taken from ubuntu's docker-net upstart config and adopted to init script
# original author: Serge Hallyn <serge.hallyn@canonical.com>

{% set vmdata = salt['mc_cloud_vm.settings']() %}
{% set data = vmdata.vts.docker.defaults %}

USE_DOCKER_BRIDGE="{{data.use_bridge}}"
USE_DOCKER_BRIDGE="{{data.use_bridge}}"
DOCKER_MAKINA_BRIDGE="{{data.bridge}}"
DOCKER_MAKINA_ADDR="{{data.gateway}}"
DOCKER_MAKINA_NETMASK="{{data.netmask_full}}"
DOCKER_MAKINA_NETWORK="{{data.network}}/{{data.netmask}}"
varrun="/var/run/docker"
DOCKER_DOMAIN=""
DOCKER_MAKINA_DOMAIN=""

. /lib/lsb/init-functions

start() {
    [ -f /etc/default/docker ] && . /etc/default/docker

    [ "x$USE_DOCKER_BRIDGE" = "xtrue" ] || { exit 0; }

    if [ -d /sys/class/net/${DOCKER_MAKINA_BRIDGE} ]; then
        if [ ! -f ${varrun}/network_up ]; then
            # bridge exists, but we didn't start it
            exit 0;
        fi
        exit 0;
    fi

    cleanup() {
        # dnsmasq failed to start, clean up the bridge
        iptables -t nat -D POSTROUTING -s ${DOCKER_MAKINA_NETWORK} ! -d ${DOCKER_MAKINA_NETWORK} -j MASQUERADE || true
        ifconfig ${DOCKER_MAKINA_BRIDGE} down || true
        brctl delbr ${DOCKER_MAKINA_BRIDGE} || true
    }

    # set up the docker network
    brctl addbr ${DOCKER_MAKINA_BRIDGE} || { echo "Missing bridge support in kernel"; exit 0; }
    echo 1 > /proc/sys/net/ipv4/ip_forward
    mkdir -p ${varrun}
    ifconfig ${DOCKER_MAKINA_BRIDGE} ${DOCKER_MAKINA_ADDR} netmask ${DOCKER_MAKINA_NETMASK} up
    iptables -t nat -A POSTROUTING -s ${DOCKER_MAKINA_NETWORK} ! -d ${DOCKER_MAKINA_NETWORK} -j MASQUERADE

    DOCKER_MAKINA_DOMAIN_ARG=""
    if [ -n "$DOCKER_MAKINA_DOMAIN" ]; then
        DOCKER_MAKINA_DOMAIN_ARG="-s $DOCKER_MAKINA_DOMAIN"
    fi
    touch ${varrun}/network_up
}

stop() {
    [ -f /etc/default/docker ] && . /etc/default/docker
    [ -f "${varrun}/network_up" ] || exit 0;
    # if $DOCKER_MAKINA_BRIDGE has attached interfaces, don't shut it down
    ls /sys/class/net/${DOCKER_MAKINA_BRIDGE}/brif/* > /dev/null 2>&1 && exit 0;

    if [ -d /sys/class/net/${DOCKER_MAKINA_BRIDGE} ]; then
        ifconfig ${DOCKER_MAKINA_BRIDGE} down
        iptables -t nat -D POSTROUTING -s ${DOCKER_MAKINA_NETWORK} ! -d ${DOCKER_MAKINA_NETWORK} -j MASQUERADE || true
        brctl delbr ${DOCKER_MAKINA_BRIDGE}
    fi
    rm -f ${varrun}/network_up
}

case "${1}" in
    start)
        log_daemon_msg "Starting Linux Containers"

        start
        ;;

    stop)
        log_daemon_msg "Stopping Linux Containers"

        stop
        ;;

    restart|force-reload)
        log_daemon_msg "Restarting Linux Containers"

        stop
        start
        ;;
esac
# vim:set et sts=4 ts=4 tw=80:
