#!/bin/sh
### BEGIN INIT INFO
# Provides:          ms_iptables
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iptables firewall
# Description:       ms_iptables is a simple iptable based firewall
### END INIT INFO

#
# Author: Mathieu Le Marec - Pasquet <kiorky@cryptelium.net>
#

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="dynamic firewall daemon (iptables)"
NAME=ms_iptables

DAEMON=/usr/bin/ms_iptables.py

SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
if [ ! -x "${DAEMON}" ];then
    echo "ms_iptables.py is not installed"
    exit 0
fi
if [  -f "/etc/default/$NAME" ];then . "/etc/default/$NAME";fi

# Define LSB log_* functions.
. /lib/lsb/init-functions

do_stop()
{
    if [ "x${MS_IPTABLES_DISABLED}" = "x" ];then
        "${DAEMON}" --stop
    else
        echo "$0: ms_iptables is disabled"
    fi
    return $?
}

do_start()
{
    if [ "x${MS_IPTABLES_DISABLED}" = "x" ];then
        "${DAEMON}"
    else
        echo "$0: ms_iptables is disabled"
    fi
    return $?
}

do_reload()
{
    if [ "x${MS_IPTABLES_DISABLED}" = "x" ];then
        do_stop
        do_start
    else
        echo "$0: ms_iptables is disabled"
    fi
    return $?

}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    log_end_msg $?
    ;;
  reload|force-reload)
    log_daemon_msg "Reloading $DESC" "$NAME"
    do_reload
    log_end_msg $?
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|reload|status}" >&2
    exit 3
    ;;
esac
