---
- name: "ms_localsettings_nscd preflight check - SKIPTEST"
  debug:
    msg: '{{True}}'
  register: ms_localsettings_nscd_can_run
  tags: ms_localsettings_nscd
- include: run.yml
  when: '{{ ms_localsettings_nscd_can_run.msg == True }}'
  tags: ms_localsettings_nscd
