---
- name: install prerequisites
  package:
    name: "{{item}}"
    state: present
  with_items: '{{ms_localsettings_sudo_vars.packages}}'
  when: |
      {{ms_localsettings_sudo_vars.packages is not none and
        ms_localsettings_sudo_vars.packages|length > 0}}
  tags: ms_localsettings_sudo
- name: files
  file:
    path: "{{item.path}}"
    state: "{{item.state|default(omit)}}"
    mode: "{{item.mode|default(omit)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
  with_items: "{{ms_localsettings_sudo_vars.files}}"
  when: |
    {{ms_localsettings_sudo_vars.files is not none and
      ms_localsettings_sudo_vars.files|length > 0}}
  tags: ms_localsettings_sudo
- name: configs
  template:
    src: "../templates/{{item.name}}"
    dest: "{{item.name}}"
    mode: "{{item.mode|default(omit)}}"
    owner: "{{item.owner|default(omit)}}"
    group: "{{item.group|default(omit)}}"
  with_items: "{{ms_localsettings_sudo_vars.configs}}"
  when: |
    {{ms_localsettings_sudo_vars.configs is not none and
      ms_localsettings_sudo_vars.configs|length > 0}}
  tags: ms_localsettings_sudo
