#!/usr/bin/env bash
API_VERSION="{{api_version}}"
HERE="${PWD}"
PROJECT_NAME="{{name}}"
FORCE_MARKER="{{FORCE_MARKER}}"
export PATH="{{WC}}/bin:${PATH}"
ret="1"
unset GIT_DIR
unset GIT_PREFIX
. /etc/profile
while read OLDREV NEWREV REF
do
BRANCH="$(echo ${REF}|awk -F"/" '{print $3}')"
echo "GOT: ${OLDREV} ${NEWREV} ${REF} / ${BRANCH}"
PY="${VENV}/bin/python"
LOGLEVEL="${LOGLEVEL:-info}"
EXTRA_ARGS=""
if [ -e "${FORCE_MARKER}" ];then
    echo "Pushing from local copy, authorized"
    rm -f "${FORCE_MARKER}"
    ret="0"
elif [ "x${BRANCH}"  = "xmaster" ];then
    if [ "x${TIMEOUT}" != "x" ];then
        EXTRA_ARGS="${EXTRA_ARGS} --timeout $TIMEOUT"
    fi
    python\
        "${HERE}/hooks/deploy_hook.py"\
        -p ${PROJECT_NAME}\
        -l "${LOGLEVEL}"\
        ${EXTRA_ARGS}
    ret=${?}
fi
if [ "x${ret}" != "x0" ];then
    if [ -f hooks/curcom ];then
        cid="$(cat hooks/curcom)"
        echo "Reverting to ${cid}"
        echo "${cid}">refs/heads/master
        exit ${ret}
    else
        echo "Undetermined old rev!"
    fi
fi
done
# vim:set et sts=4 ts=4 tw=80 ft=bash:
